environment: DEV

paths:
  input_dir: workspace/input
  output_dir: workspace/output
  template_dir: frontend
  logs_dir: workspace/logs
  cache_dir: workspace/cache

excel:
  pattern: "ControlPases*.xlsx"

branding:
  logo: frontend/assets/images/BCP.png
  partner_logo: frontend/assets/images/Kyndryl.png

app:
  name: "Change Triage"
  subtitle: "Portal de Validación de Cambios en Producción"
  timezone: "America/Lima"
